highlighter: rouge
permalink: /:year/:month/:title
markdown: kramdown
name: Marcin Świerczyński's Blog
description: A personal blog about software engineering
url: http://blog.swierczynski.net

 # PAGINATION
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
